export enum OmbiRequestState {
  NONE = 'NONE',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  APPROVED_REQUEST = 'APPROVED_REQUEST',
  DECLINED_REQUEST = 'DECLINED_REQUEST',
  PARTIALLY_AVAILABLE = 'PARTIALLY_AVAILABLE',
  AVAILABLE = 'AVAILABLE',
}
