export enum ExitCode {
  SUCCESS = 0,
  UNCAUGHT_FATAL_EXCEPTION = 1,
  INTERNAL_JAVASCRIPT_PARSE_ERROR = 3,
  INTERNAL_JAVASCRIPT_EVALUATION_FAILURE = 4,
  FATAL_UNRECOVERABLE_ERROR = 5,
  NON_FUNCTION_INTERNAL_EXCEPTION_HANDLER = 6,
  INTERNAL_EXCEPTION_HANDLER_RUNTIME_FAILURE = 7,
  INVALID_ARGUMENT = 9,
  INTERNAL_JAVASCRIPT_RUNTIME_FAILURE = 10,
  INVALID_DEBUG_ARGUMENT = 12,
  COMMAND_LINE_USAGE_ERROR = 64,
  DATA_FORMAT_ERROR = 65,
  INPUT_FILE_ERROR = 66,
  UNKNOWN_ADDRESSEE = 67,
  UNKNOWN_HOST_NAME = 68,
  UNAVAILABLE_SERVICE = 69,
  SOFTWARE_ERROR = 70,
  OPERATING_SYSTEM_ERROR = 71,
  MISSING_CRITICAL_OPERATING_SYSTEM_FILE = 72,
  OUTPUT_FILE_ERROR = 73,
  IO_ERROR = 74,
  TEMPORARY_FAILURE = 75,
  PROTOCOL_ERROR = 76,
  PERMISSION_DENIED = 77,
  CONFIGURATION_ERROR = 78,
  SIGHUP = 129,
  SIGINT = 130,
  SIGQUIT = 131,
  SIGILL = 132,
  SIGTRAP = 133,
  SIGABRT = 134,
  SIGIOT = 134,
  SIGBUS = 135,
  SIGFPE = 136,
  SIGKILL = 137,
  SIGUSR1 = 138,
  SIGSEGV = 139,
  SIGUSR2 = 140,
  SIGPIPE = 141,
  SIGALRM = 142,
  SIGTERM = 143,
  SIGSTKFLT = 144,
  SIGCHLD = 145,
  SIGCONT = 146,
  SIGSTOP = 147,
  SIGTSTP = 148,
  SIGTTIN = 149,
  SIGTTOU = 150,
  SIGURG = 151,
  SIGXCPU = 152,
  SIGXFSZ = 153,
  SIGVTALRM = 154,
  SIGPROF = 155,
  SIGWINCH = 156,
  SIGIO = 157,
  SIGPOLL = 157,
  SIGPWR = 158,
  SIGINFO = 158,
  SIGSYS = 159,
}

export const exitCodeMeanings: Record<number, string> = {
  [ExitCode.SUCCESS]: 'finished successfully',
  [ExitCode.UNCAUGHT_FATAL_EXCEPTION]: 'exited due to uncaught fatal exception',
  [ExitCode.INTERNAL_JAVASCRIPT_PARSE_ERROR]: 'exited due to internal javascript parse error',
  [ExitCode.INTERNAL_JAVASCRIPT_EVALUATION_FAILURE]: 'exited due to internal javascript evaluation failure',
  [ExitCode.FATAL_UNRECOVERABLE_ERROR]: 'exited due to fatal unrecoverable error in V8',
  [ExitCode.NON_FUNCTION_INTERNAL_EXCEPTION_HANDLER]: 'exited due to non-function internal exception handler',
  [ExitCode.INTERNAL_EXCEPTION_HANDLER_RUNTIME_FAILURE]: 'exited due to internal exception handler runtime failure',
  [ExitCode.INVALID_ARGUMENT]: 'exited due to invalid argument',
  [ExitCode.INTERNAL_JAVASCRIPT_RUNTIME_FAILURE]: 'exited due to internal javascript runtime failure',
  [ExitCode.INVALID_DEBUG_ARGUMENT]: 'exited due to invalid debug argument',
  [ExitCode.COMMAND_LINE_USAGE_ERROR]: 'exited due to command line usage error',
  [ExitCode.DATA_FORMAT_ERROR]: 'exited due to data format error',
  [ExitCode.INPUT_FILE_ERROR]: 'exited due to input file not existing or not readable',
  [ExitCode.UNKNOWN_ADDRESSEE]: 'exited due to unknown addressee',
  [ExitCode.UNKNOWN_HOST_NAME]: 'exited due to unknown host name',
  [ExitCode.UNAVAILABLE_SERVICE]: 'exited due to unavailable service',
  [ExitCode.SOFTWARE_ERROR]: 'exited due to software error',
  [ExitCode.OPERATING_SYSTEM_ERROR]: 'exited due to operating system error',
  [ExitCode.MISSING_CRITICAL_OPERATING_SYSTEM_FILE]: 'exited due to missing critical operating system file',
  [ExitCode.OUTPUT_FILE_ERROR]: 'exited due to not being able to create output file',
  [ExitCode.IO_ERROR]: 'exited due to input/output error',
  [ExitCode.TEMPORARY_FAILURE]: 'exited due to temporary failure',
  [ExitCode.PROTOCOL_ERROR]: 'exited due to protocol error',
  [ExitCode.PERMISSION_DENIED]: 'exited due to permission denied',
  [ExitCode.CONFIGURATION_ERROR]: 'exited due to configuration error',
  [ExitCode.SIGHUP]: 'exited due to unhandled "Hangup detected on controlling terminal or death of controlling process" signal [SIGHUP]',
  [ExitCode.SIGINT]: 'exited due to unhandled "Interrupt from keyboard" signal [SIGINT]',
  [ExitCode.SIGQUIT]: 'exited due to unhandled "Quit from keyboard" signal [SIGQUIT]',
  [ExitCode.SIGILL]: 'exited due to unhandled "Illegal Instruction" signal [SIGILL]',
  [ExitCode.SIGTRAP]: 'exited due to unhandled "Trace/breakpoint trap" signal [SIGTRAP]',
  [ExitCode.SIGABRT]: 'exited due to unhandled abort signal [SIGABRT/SIGIOT]',
  [ExitCode.SIGBUS]: 'exited due to unhandled "Bus error (bad memory access)" signal [SIGBUS]',
  [ExitCode.SIGFPE]: 'exited due to unhandled "Floating-point exception" signal [SIGFPE]',
  [ExitCode.SIGKILL]: 'exited due to Kill signal [SIGKILL]',
  [ExitCode.SIGUSR1]: 'exited due to unhandled "User-defined signal 1" signal [SIGUSR1]',
  [ExitCode.SIGSEGV]: 'exited due to unhandled "Invalid memory reference" signal [SIGSEGV]',
  [ExitCode.SIGUSR2]: 'exited due to unhandled "User-defined signal 2" signal [SIGUSR2]',
  [ExitCode.SIGPIPE]: 'exited due to unhandled "Broken pipe" signal [SIGPIPE]',
  [ExitCode.SIGALRM]: 'exited due to unhandled alarm signal [SIGALRM]',
  [ExitCode.SIGTERM]: 'exited due to unhandled "Termination signal" signal [SIGTERM]',
  [ExitCode.SIGSTKFLT]: 'exited due to unhandled "Stack fault on coprocessor" signal [SIGSTKFLT]',
  [ExitCode.SIGCHLD]: 'exited due to unhandled "Child stopped or terminated" signal [SIGCHLD]',
  [ExitCode.SIGCONT]: 'exited due to unhandled "Continue if stopped" signal [SIGCONT]',
  [ExitCode.SIGSTOP]: 'exited due to unhandled "Stop process" signal [SIGSTOP]',
  [ExitCode.SIGTSTP]: 'exited due to unhandled "Stop typed at terminal" signal [SIGTSTP]',
  [ExitCode.SIGTTIN]: 'exited due to unhandled "Terminal input for background process" signal [SIGTTIN]',
  [ExitCode.SIGTTOU]: 'exited due to unhandled "Terminal output for background process" signal [SIGTTOU]',
  [ExitCode.SIGURG]: 'exited due to unhandled "Urgent condition on socket" signal [SIGURG]',
  [ExitCode.SIGXCPU]: 'exited due to unhandled "CPU time limit exceeded" signal [SIGXCPU]',
  [ExitCode.SIGXFSZ]: 'exited due to unhandled "File size limit exceeded" signal [SIGXFSZ]',
  [ExitCode.SIGVTALRM]: 'exited due to unhandled "Virtual alarm clock" signal [SIGVTALRM]',
  [ExitCode.SIGPROF]: 'exited due to unhandled "Profiling timer expired" signal [SIGPROF]',
  [ExitCode.SIGWINCH]: 'exited due to unhandled "Window resize" signal [SIGWINCH]',
  [ExitCode.SIGIO]: 'exited due to unhandled "Pollable event" signal [SIGIO/SIGPOLL]',
  [ExitCode.SIGPWR]: 'exited due to unhandled "Power failure" signal [SIGPWR/SIGINFO]',
  [ExitCode.SIGSYS]: 'exited due to unhandled "Bad system call" signal [SIGSYS]',
};
